### Get all nodes.

GET http://localhost:3003/api/blogs HTTP/1.1



### Deleting a note.

DELETE http://localhost:3003/api/blogs/2 HTTP/1.1



### Adding a note.

POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
  "title": "Blog No 1",
  "author": "John Doe",
  "url": "linkhere",
  "likes": 3
}

